language: rust

addons:
  apt:
    packages:
    - pandoc
    - libxml2-utils

matrix:
  include:
    - env: TARGET=docs
      script:
        - find . -name '*.md' -print0 | xargs -0 mdcheckr
    - env: TARGET=sml
      rust: stable
      script:
        - cargo check
        - cargo test

before_install: set -e

install:
  - bash ci/install.sh
  - export PATH="$PATH:$PWD/mdcheck"

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
